import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <main style="min-height:100vh;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:2rem;padding:2rem">
      <h1 style="font-size:2rem;font-weight:700;color:#28251d">
        🤖 Example Counter POC
      </h1>
      <p style="color:#7a7974;font-size:0.9rem">Auto-generated by Gemini AI via Telegram Bot</p>

      <div style="background:white;border-radius:1rem;padding:3rem;box-shadow:0 4px 24px rgba(0,0,0,0.08);text-align:center;min-width:280px">
        <div style="font-size:5rem;font-weight:700;color:#01696f;line-height:1">{{ count() }}</div>
        <div style="color:#7a7974;margin:0.5rem 0 2rem;font-size:0.85rem">{{ label() }}</div>
        <div style="display:flex;gap:0.75rem;justify-content:center">
          <button (click)="decrement()" style="padding:0.75rem 1.5rem;border-radius:0.5rem;border:1px solid #d4d1ca;background:white;cursor:pointer;font-size:1.25rem">−</button>
          <button (click)="reset()" style="padding:0.75rem 1.5rem;border-radius:0.5rem;border:1px solid #d4d1ca;background:white;cursor:pointer;font-size:0.85rem;color:#7a7974">Reset</button>
          <button (click)="increment()" style="padding:0.75rem 1.5rem;border-radius:0.5rem;border:none;background:#01696f;color:white;cursor:pointer;font-size:1.25rem">+</button>
        </div>
      </div>
    </main>
  `
})
export class AppComponent {
  count = signal(0);
  label = computed(() => {
    const c = this.count();
    if (c === 0) return 'Start clicking!';
    if (c > 0) return `${c} click${c !== 1 ? 's' : ''}`;
    return `${Math.abs(c)} below zero`;
  });

  increment() { this.count.update(v => v + 1); }
  decrement() { this.count.update(v => v - 1); }
  reset() { this.count.set(0); }
}
